### ISSUE TITLE
1b & 1c Todos

### ISSUE THREAD

**Issue by gusluchetti** [gusluchetti/uu-methods-ai-research#10]
- [x] Make sure both sklearn models work properly.
- [x] Save models so we don't have to rebuild them (w/ `import pickle`)

### Quality of Life
- [x] update .gitignore for saved models / change files to .sav(?)
- [x] poetry + .pyenv to build the project
- [ ] Run evaluate step on full rebuild of models. (and output interesting data to another file that we can query.

**Comment by gusluchetti** [comment]
## To-dos
- [ ] Make sure bot works.
- [ ] Add logging/better testing features.
- [ ] Add tests (pytest)
- [ ] Upgrade project structure.
- [ ] Start working on configurability.

**Comment by gusluchetti** [comment]
delete world and swedish values on type match (not present on any of the restaurants)
add romanian
